services:
  db:
    container_name: code-academy-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: code_academy
      MYSQL_USER: code_user
      MYSQL_PASSWORD: code_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app_network

  php:
    container_name: code-academy-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./api:/var/www/
    working_dir: /var/www
    depends_on:
      - db
    expose:
      - 9000
    networks:
      - app_network

  proxy:
    container_name: code-academy-proxy
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app_network

  web:
    container_name: code-academy-web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    working_dir: /var/app
    volumes:
      - ./web:/var/app
    user: "1000:1000"
    ports:
      - "3001:3000"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge