services:
  code-academy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-academy
    working_dir: /var/www
    user: "1000:1000"
    volumes:
      - ./:/var/www
      - /var/www/.next
      - /var/www/node_modules
    restart: unless-stopped
    networks:
      - shared-net

networks:
  shared-net:
    external: true